config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }
  root 'home#top'
  get 'home/about'
  get '/search' => 'search#search'
  resources :users, only: [:show, :edit, :update, :index]
  get 'users/:id/follows' => 'users#following', as: 'follows'
  get 'users/:id/followers' => 'users#followers', as: 'followers'
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]do
  	resources :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # 住所機能
  include JpPrefecture
  jp_prefecture :prefecture_code
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  attachment :profile_image, destroy: false

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  geocoded_by :full_address
  after_validation :geocode if :prefecture_code_changed?
  # after_validation :geocode, if: :prefecture_code_changed?

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  validates :postcode, presence: true
  validates :prefecture_code, presence: true
  validates :address_city, presence: true
  validates :address_street, presence: true

  #ユーザーをフォローする
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  #ユーザーのフォローを解除する
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
  #すでにフォロー済みであればture返す
  def following?(other_user)
    self.followings.include?(other_user)
  end

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  def full_address
    full_address = prefecture_name + address_city + address_street + address_building
    # prefecture_name + address_city + address_street + address_building
    # [prefecture_name, address_city, address_street, address_building].join(" ")
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    UserNotifierMailer.send_signup_email(@user).deliver
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
	before_action :correct_user, only: [:edit, :update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render 'edit'
  	end
  end

    #フォローしてる人たち
  def following
  @user = User.find(params[:id])
  @users = @user.followings.all
  end

  #フォローしてくれてる人たち
  def followers
  @user = User.find(params[:id])
  @users = @user.followers.all
  end





  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image, :postcode, :prefecture_code, :address_city, :address_street, :address_building, :latitude, :longitude)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def correct_user
      @user = User.find(params[:id])
      redirect_to user_path(current_user) if current_user != @user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_map.html.erb
<h2>Your MAP</h2>
〒<%= current_user.postcode %>
<%=current_user.full_address%><br>

code：<%=current_user.prefecture_code%><br>

緯度：<%= current_user.latitude %><br>
経緯：<%= current_user.longitude %>
<!-- geocoderでは市までしか変換できない -->

<!-- 下の1行を追加 -->
<div id="display"></div>

<!-- <div id='map'></div>
 -->


<!-- geocoderを使わない方法 -->
 <iframe src="https://maps.google.co.jp/maps?output=embed&q=<%=current_user.full_address%>&z=16" width="100%" height="400" frameborder="0" scrolling="no" ></iframe>


<style>
#map {
  height: 600px;
  width: 100%;
}
</style>

<script>
let map
let geocoder
// 下の1行を追加
const display = document.getElementById('display')

function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 40.7828, lng:-73.9653},
    zoom: 12,
  });

  marker = new google.maps.Marker({
    position:  {lat: 40.7828, lng:-73.9653},
    map: map
  });
}
</script>


<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLEMAP_API_KEY"] %>&callback=initMap" async defer></script>

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>

		<tr>
			<th>follows</th>
			<th> <%= link_to user.followings.count, follows_path(user.id) %></th>
		</tr>

		<tr>
			<th>followers</th>
			<th> <%= link_to user.followers.count, followers_path(user.id) %></th>
		</tr>
		</table>

			<% unless current_user == user %>
			  <% if current_user.following?(user) %>
			    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
			      <%= f.hidden_field :follow_id, value: user.id %>
			      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
			    <% end %>
			  <% else %>
			    <%= form_for(current_user.relationships.build) do |f| %>
			      <%= f.hidden_field :follow_id, value: user.id %>
			      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
			    <% end %>
			  <% end %>
			<% end %>


<% if current_user == user %>
<div class="row">
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<!-- 住所 -->
  <div class="field">
    <%= f.label :postcode %><br />
    <%= f.text_field :postcode, autofocus: true,　placeholder:'郵便番号を半角で入力',  class: "postcode" %>
  </div>

  <div class="field">
    <%= f.label :prefecture_code %><br />
    <%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name, include_blank: '都道府県', class: "prefecture_code" %>
  </div>

  <div class="field">
    <%= f.label :address_city %><br />
    <%= f.text_field :address_city, autofocus: true,　placeholder: '市町名を入力', class: "address_city" %>
  </div>

  <div class="field">
    <%= f.label :address_street %><br />
    <%= f.text_field :address_street, autofocus: true,　placeholder: '町名・番地', class: "address_street" %>
  </div>

  <div class="field">
    <%= f.label :address_building %><br />
    <%= f.text_field :address_building, autofocus: true,　placeholder: '建物、部屋番号を入力', class: "address_building" %>
  </div>


<div class="actions">
	<%= f.submit %>
</div>


<% end %>


<!-- 39 codeの前はname -->

app/views/users/followers.html.erb
<div class="row">

<div class="col-xs-9">
	<h2>Follow Users</h2>
	<!--users一覧 -->
	<table class="table">
		<thead>
			<tr>
				<th>image</th>
				<th>name</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @users.each do |user| %>
			<tr>
				<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
				<td><%= user.name %></td>
				<td><%= user.followings.count %></td>
				<td><%= user.followers.count %></td>

				<!-- フォロー -->
				<% unless current_user == user %>
				<td>
				  <% if current_user.following?(user) %>
				    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
				      <%= hidden_field_tag :follow_id, user.id %>
				      <%= f.submit 'Unfollow' %>
				    <% end %>
				  <% else %>
				    <%= form_for(current_user.relationships.build) do |f| %>
				      <%= hidden_field_tag :follow_id, user.id %>
				      <%= f.submit 'Follow' %>
				    <% end %>
				  <% end %>
				  <% else %>
				  <td></td>
				<% end %>
			  </td>

				<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

</div>

app/views/users/following.html.erb
<div class="row">

<div class="col-xs-9">
	<h2>Follower Users</h2>
	<!--users一覧 -->
	<table class="table">
		<thead>
			<tr>
				<th>image</th>
				<th>name</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @users.each do |user| %>
			<tr>
				<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
				<td><%= user.name %></td>
				<td><%= user.followings.count %></td>
				<td><%= user.followers.count %></td>

				<!-- フォロー -->
				<% unless current_user == user %>
					<td>
						<% if current_user.following?(user) %>
							<%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
								<%= f.hidden_field :follow_id, value: user.id %>
								<%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
							<% end %>
						<% else %>
							<%= form_for(current_user.relationships.build) do |f| %>
								<%= f.hidden_field :follow_id, value: user.id %>
								<%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
							<% end %>
						<% end %>
					</td>
				<% else %>
					<td></td>
				<% end %>

				<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

</div>

app/views/users/index.html.erb
<div class="row">

<div class="col-xs-3">
<h2>User info</h2>
	<%= render 'users/profile', user: current_user %>
	<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

	<h2>New book</h2>
	<%= render 'books/newform', book: Book.new %>
</div>

<div class="col-xs-9">
	<h2>Users</h2>
	<!--users一覧 -->
	<table class="table">
		<thead>
			<tr>
				<th>image</th>
				<th>name</th>
				<th>followers</th>
				<th>follow</th>
				<th>show</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @users.each do |user| %>
			<tr>
				<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
				<td><%= user.name %></td>
				<td><%= link_to user.followers.count, followers_path(user.id) %></td>

				<!-- フォロー -->
				<% unless current_user == user %>
					<td>
						<% if current_user.following?(user) %>
							<%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
								<%= f.hidden_field :follow_id, value: user.id %>
								<%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
							<% end %>
						<% else %>
							<%= form_for(current_user.relationships.build) do |f| %>
								<%= f.hidden_field :follow_id, value: user.id %>
								<%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
							<% end %>
						<% end %>
					</td>
				<% else %>
					<td></td>
				<% end %>


				<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

</div>
<!--users一覧 -->

app/views/users/show.html.erb
<div class="row">

<div class="col-xs-3">
	<h2>User info</h2>
	<%= render 'users/profile', user: @user %>
	<!--同コントローラーのviewで表示ならusersは省略可 -->

	<h2>New book</h2>
	<%= render 'books/newform', book: Book.new %>
</div>

<div class="col-xs-9">
	<h2>Books</h2>
	<!--books一覧 -->
	<table class="table table-hover table-inverse">
		<thead>
			<tr>
				<th>image</th>
				<th>Title</th>
				<th>Opinion</th>
				<th>like</th>
				<th>comment</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @books.each do |book| %>
			<tr>
				<td>
					<%= link_to (book.user) do %>
					<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
					<% end %>
				</td>
				<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
				<td><%= book.body %></td>

				<!-- いいね -->
					<td id="like-<%= book.id %>">
						<%= render 'favorites/favorite', book: book %>
					</td>
					<!-- コメント数 -->
					<td>
						<i class="fa fa-comment"></i>
						<%= book.book_comments.count %> コメント
					</td>

			</tr>
			<% end %>
		</tbody>
	</table>
</div>

</div>

<!--map -->
<% if current_user.id == @user.id %>
	<div class="row">
		<%= render 'users/map' %>
	</div>
<% end %>