config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }
  root 'home#top'
  get 'home/about'
  get '/search' => 'search#search'
  resources :users, only: [:show, :edit, :update, :index]
  get 'users/:id/follows' => 'users#following', as: 'follows'
  get 'users/:id/followers' => 'users#followers', as: 'followers'
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]do
  	resources :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
     end

	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!,only: [:create,:edit,:update,:destroy,:index]
  before_action :correct_user, only: [:edit, :update, :destroy,]

  def show
  	@book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def index
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book = Book.new
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render 'edit'
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body, :user_id)
  end

  def correct_user
      @book = Book.find(params[:id])
      redirect_to books_path if current_user != @book.user
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<% if @book.errors.any? %>
    <div id="error_explanation">
        <h3><%= @book.errors.count %>errors prohibited this obj from being saved</h3>
        <ul>
            <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= render 'books/newform', book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<% if @book.errors.any? %>
		    <div id="error_explanation">
		        <h3><%= @book.errors.count %>errors prohibited this obj from being saved</h3>
		        <ul>
		            <% @book.errors.full_messages.each do |message| %>
		                <li><%= message %></li>
		            <% end %>
		        </ul>
		    </div>
		<% end %>

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: Book.new %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th>image</th>
					<th>Title</th>
					<th>Opinion</th>
					<th>like</th>
					<th>comment</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>

					<!-- いいね -->
					<td id="like-<%= book.id %>">
						<%= render 'favorites/favorite', book: book %>
					</td>
					<td>
						<i class="fa fa-comment"></i>
						<%= book.book_comments.count %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @book.user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: Book.new %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>Title</th>
					<th>Opinion</th>
					<th>like</th>
					<th>comment</th>
					<th colspan="3"></th>
				</tr>
			</thead>
				<tr>
					<!-- 写真・名前 -->
					<td>
						<%= link_to user_path(@book.user_id) do %>
						<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<!-- title -->
					<td><%= link_to @book.title, book_path(@book) %></td>
					<!-- body -->
					<td><%= @book.body %></td>
					<!-- いいね -->
					<td id="like-<%= @book.id %>">
						<%= render 'favorites/favorite', book: @book %>
					</td>
					<!-- コメント数 -->
					<td>
						<i class="fa fa-comment"></i>
						<%= @book.book_comments.count %> コメント
					</td>
					<!-- 編集・削除 -->
					<% if @book.user_id == current_user.id %>
					<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
			</table>


			<!-- コメント一覧 -->
			<div id="comments_area">
				<%= render 'book_comments/comments', book: @book %>
			</div>

			<!-- 投稿エラー文 -->


			<!-- コメント投稿 -->
			<%= form_with(model: [@book, @book_comment]) do |f| %>
			    <div class="row">
			        <div class="col-sm-12">
			            <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
			        </div>
			    </div>
			    <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
			<% end %>






	</div>
</div>



<!-- form_withはデフォルトでtrueがある -->